# Add i18n msgids here which do not exist in filesystem code so that
# the translation-extract script can find them

from osha.policy import recensioMessageFactory as _

# FOP
_("heading_main_fop_portlet_albania")
_("heading_main_fop_portlet_austria")
_("heading_main_fop_portlet_belgium")
_("heading_main_fop_portlet_bosnia-and-herzegovina")
_("heading_main_fop_portlet_bulgaria")
_("heading_main_fop_portlet_croatia")
_("heading_main_fop_portlet_cyprus")
_("heading_main_fop_portlet_czech-republic")
_("heading_main_fop_portlet_denmark")
_("heading_main_fop_portlet_estonia")
_("heading_main_fop_portlet_finland")
_("heading_main_fop_portlet_france")
_("heading_main_fop_portlet_germany")
_("heading_main_fop_portlet_greece")
_("heading_main_fop_portlet_hungary")
_("heading_main_fop_portlet_iceland")
_("heading_main_fop_portlet_ireland")
_("heading_main_fop_portlet_italy")
_("heading_main_fop_portlet_kosovo-under-unscr-1244-99")
_("heading_main_fop_portlet_latvia")
_("heading_main_fop_portlet_liechtenstein")
_("heading_main_fop_portlet_lithuania")
_("heading_main_fop_portlet_luxembourg")
_("heading_main_fop_portlet_malta")
_("heading_main_fop_portlet_montenegro")
_("heading_main_fop_portlet_netherlands")
_("heading_main_fop_portlet_norway")
_("heading_main_fop_portlet_poland")
_("heading_main_fop_portlet_portugal")
_("heading_main_fop_portlet_romania")
_("heading_main_fop_portlet_serbia")
_("heading_main_fop_portlet_slovakia")
_("heading_main_fop_portlet_slovenia")
_("heading_main_fop_portlet_spain")
_("heading_main_fop_portlet_sweden")
_("heading_main_fop_portlet_switzerland")
_("heading_main_fop_portlet_the-former-yugoslav-republic-of-macedonia")
_("heading_main_fop_portlet_turkey")
_("heading_main_fop_portlet_united-kingdom")
_("label_back_to_fop_overview")

# NAPO
_("description_napo-015-safe-moves")
_("description_napo-016-lungs-at-work")
_("description_napo-017-working-together")
_("description_napo_film_1")
_("description_napo_film_11")
_("description_napo_film_12")
_("description_napo_film_13")
_("description_napo_film_14")
_("description_napo_film_2")
_("description_napo_film_3")
_("description_napo_film_4")
_("description_napo_film_5")
_("description_napo_film_6")
_("description_napo_film_7")
_("description_napo_film_8")
_("description_napo_film_9")
_("heading_napo-015-safe-moves")
_("heading_napo-015-safe-moves-episode-001-planning-for-safety")
_("heading_napo-015-safe-moves-episode-002-danger-unloading")
_("heading_napo-015-safe-moves-episode-003-poor-maintenance")
_("heading_napo-015-safe-moves-episode-004-carried-away")
_("heading_napo-015-safe-moves-episode-005-separate-ways")
_("heading_napo-015-safe-moves-episode-006-circus-number")
_("heading_napo-015-safe-moves-episode-007-unstable-load")
_("heading_napo-015-safe-moves-episode-008-clear-vision")
_("heading_napo-015-safe-moves-episode-009-danger-calling")
_("heading_napo-015-safe-moves-episode-010-the-end-game")
_("heading_napo-016-lungs-at-work")
_("heading_napo-017-working-together")
_("heading_napo-017-working-together-episode-001-working-together")
_("heading_napo-017-working-together-episode-002-bad-news")
_("heading_napo-017-working-together-episode-003-the-detail")
_("heading_napo-017-working-together-episode-004-we-can-work-it-out")
_("heading_napo-017-working-together-episode-005-speak-up")
_("heading_napo-017-working-together-episode-006-safety-pays")
_("heading_napo-017-working-together-episode-007-all-together-now")
_("label_napo_click_to_see_film")
_("napo_back_to_lesson")
_("title_napo_episode_12_1")
_("title_napo_episode_12_2")
_("title_napo_episode_12_3")
_("title_napo_episode_12_4")
_("title_napo_episode_12_5")
_("title_napo_episode_12_6")
_("title_napo_episode_12_7")
_("title_napo_episode_12_8")
_("title_napo_episode_14_1")
_("title_napo_episode_14_2")
_("title_napo_episode_14_3")
_("title_napo_episode_14_4")
_("title_napo_episode_14_5")
_("title_napo_episode_14_6")
_("title_napo_episode_1_0")
_("title_napo_episode_1_1")
_("title_napo_episode_1_10")
_("title_napo_episode_1_11")
_("title_napo_episode_1_12")
_("title_napo_episode_1_13")
_("title_napo_episode_1_14")
_("title_napo_episode_1_15")
_("title_napo_episode_1_16")
_("title_napo_episode_1_17")
_("title_napo_episode_1_2")
_("title_napo_episode_1_3")
_("title_napo_episode_1_4")
_("title_napo_episode_1_5")
_("title_napo_episode_1_6")
_("title_napo_episode_1_7")
_("title_napo_episode_1_8")
_("title_napo_episode_1_9")
_("title_napo_episode_2_0")
_("title_napo_episode_2_1")
_("title_napo_episode_2_2")
_("title_napo_episode_2_3")
_("title_napo_episode_2_4")
_("title_napo_episode_2_5")
_("title_napo_episode_2_6")
_("title_napo_episode_2_7")
_("title_napo_episode_2_8")
_("title_napo_episode_2_9")
_("title_napo_episode_3_0")
_("title_napo_episode_3_1")
_("title_napo_episode_3_2")
_("title_napo_episode_3_3")
_("title_napo_episode_3_4")
_("title_napo_episode_3_5")
_("title_napo_episode_3_6")
_("title_napo_episode_3_7")
_("title_napo_episode_4_0")
_("title_napo_episode_4_1")
_("title_napo_episode_4_2")
_("title_napo_episode_4_3")
_("title_napo_episode_4_4")
_("title_napo_episode_4_5")
_("title_napo_episode_4_6")
_("title_napo_episode_4_7")
_("title_napo_episode_4_8")
_("title_napo_episode_5_0")
_("title_napo_episode_5_1")
_("title_napo_episode_5_2")
_("title_napo_episode_5_3")
_("title_napo_episode_5_4")
_("title_napo_episode_5_5")
_("title_napo_episode_5_6")
_("title_napo_episode_5_7")
_("title_napo_episode_5_8")
_("title_napo_episode_5_9")
_("title_napo_episode_6_0")
_("title_napo_episode_6_1")
_("title_napo_episode_6_2")
_("title_napo_episode_6_3")
_("title_napo_episode_6_4")
_("title_napo_episode_6_5")
_("title_napo_episode_6_6")
_("title_napo_episode_6_7")
_("title_napo_episode_7_0")
_("title_napo_episode_7_1")
_("title_napo_episode_7_2")
_("title_napo_episode_7_3")
_("title_napo_episode_7_4")
_("title_napo_episode_7_5")
_("title_napo_episode_7_6")
_("title_napo_episode_8_0")
_("title_napo_episode_8_1")
_("title_napo_episode_8_10")
_("title_napo_episode_8_11")
_("title_napo_episode_8_2")
_("title_napo_episode_8_3")
_("title_napo_episode_8_4")
_("title_napo_episode_8_5")
_("title_napo_episode_8_6")
_("title_napo_episode_8_7")
_("title_napo_episode_8_8")
_("title_napo_episode_8_9")
_("title_napo_episode_9_0")
_("title_napo_episode_9_1")
_("title_napo_episode_9_2")
_("title_napo_episode_9_3")
_("title_napo_episode_9_4")
_("title_napo_episode_9_5")
_("title_napo_episode_9_6")
_("title_napo_episode_9_7")
_("title_napo_film_1")
_("title_napo_film_11")
_("title_napo_film_12")
_("title_napo_film_13")
_("title_napo_film_14")
_("title_napo_film_2")
_("title_napo_film_3")
_("title_napo_film_4")
_("title_napo_film_5")
_("title_napo_film_6")
_("title_napo_film_7")
_("title_napo_film_8")
_("title_napo_film_9")

# Subjects http://osha.europa.eu/uniqueValuesForSubject
_("Practical Solutions, Good Practice")
_("accident_prevention")
_("ageing")
_("agriculture")
_("businessOSH")
_("cleaners")
_("competitions")
_("construction")
_("csr")
_("cww")
_("dangerous_substances")
_("disability")
_("disabled_people")
_("economic_incentives")
_("education")
_("esener")
_("fisheries")
_("gender")
_("green_jobs")
_("health_care")
_("healthcare")
_("horeca")
_("hwi")
_("legislation")
_("maintenance")
_("management_leadership")
_("migrant_workers")
_("msd")
_("nanotechnology")
_("noise")
_("organisation")
_("osheducation")
_("prevention")
_("provider")
_("publications")
_("research")
_("risk_assessment")
_("risk_observatory")
_("risks")
_("road_transport")
_("statistics")
_("stress")
_("transport")
_("whp")
_("worker_participation")
_("young_people")

# Already in the osha.pot file and translated
_("osha_label_press_and_multimedia")

# Months (just in case)
_("January")
_("February")
_("March")
_("April")
_("May")
_("June")
_("July")
_("August")
_("September")
_("October")
_("November")
_("December")

# These look like msgids (there's no other reason to keep them)
_("accesskeys-breadcrumbs")
_("accesskeys-navigation")
_("accesskeys-search")
_("accident_prevention")
_("action_firstlogin_proceed")
_("action_ldap_savepersonaldata")
_("action_ldap_savesecurityquestion")
_("ageing")
_("agriculture")
_("alert_day_periodical")
_("alert_no_searchqueries")
_("alertservice_information_changed")
_("alertservice_information_changed_since")
_("alertservice_notification_report")
_("alertservice_notification_sentby")
_("alertservice_onlyfirst_shown")
_("alertservice_requested_info")
_("alertservice_results_found")
_("answer")
_("answer_all")
_("april")
_("attachment")
_("august")
_("back to board")
_("back_to")
_("bcc")
_("before")
_("box_about")
_("box_created_by")
_("box_last_modified")
_("box_oshmail_subscribe")
_("box_provided_by")
_("box_search_seminars")
_("box_speaker")
_("box_speeches")
_("box_this_url")
_("businessOSH")
_("button_alert_addsearchquery")
_("calendar day view")
_("calender_hopefully")
_("cc")
_("character_coding")
_("check_link")
_("choose Paths")
_("cleaners")
_("close window")
_("close")
_("cmfcollection_body_not_visible")
_("cmfcollection_body_visible")
_("cmfmetadata_editmetadata")
_("competitions")
_("compose_link")
_("construction")
_("convert to pdf")
_("csr")
_("cww")
_("daily")
_("dangerous_substances")
_("date_ever")
_("date_last_month")
_("date_last_week")
_("date_yesterday")
_("day")
_("days")
_("december")
_("default")
_("delete")
_("delete_folder_alert")
_("delete_folder_title")
_("desc_my_working_copies")
_("desc_my_working_copies_admin")
_("description_add_alert")
_("description_add_new_item")
_("description_advanced_search")
_("description_alert_searchqueries")
_("description_change_ownership")
_("description_checkin")
_("description_cmpage_addgroup")
_("description_cmpage_editcmplink")
_("description_cmpage_editgroup")
_("description_configure_user_alreadyregistered")
_("description_configure_user_welcome")
_("description_dc_grantboard")
_("description_discard_changes")
_("description_discussionboard_configure")
_("description_discussioncenter_applyforboard")
_("description_discussioncenter_bind_boards")
_("description_discussioncenter_configure")
_("description_discussioncenter_configure_discussionboard")
_("description_document_addattachments")
_("description_document_configure")
_("description_document_editattachments")
_("description_download_file")
_("description_dynocontent_edit")
_("description_edit_document")
_("description_edit_file")
_("description_edit_item")
_("description_edit_link_item")
_("description_edit_properties")
_("description_edit_syndocument")
_("description_failed_login_link")
_("description_failed_login_link_slc_ldap")
_("description_folder_configure")
_("description_group_shares")
_("description_item_new")
_("description_ldap_assignedgroups")
_("description_ldap_assignedroles")
_("description_localrole_select_member")
_("description_logged_in_explain")
_("description_logged_out")
_("description_lost_password")
_("description_lost_password_slc_ldap")
_("description_manage_languages")
_("description_managemetadata")
_("description_metadatavalue_edit")
_("description_my_addresses")
_("description_navigation_edit")
_("description_navigation_editlink")
_("description_newbie_pointers")
_("description_newsarticle_edit")
_("description_newsboard_configure")
_("description_no_account")
_("description_no_content_in_feed")
_("description_no_default_folder_create_new")
_("description_no_items_in_feed")
_("description_no_visible_items_add_paste")
_("description_not_logged_in_username_incorrect")
_("description_not_logged_in_username_incorrect_slc_ldap")
_("description_not_versionable")
_("description_object_owned_by")
_("description_oshasite_config")
_("description_oshasite_editimages")
_("description_personal_profile")
_("description_portlet_edit")
_("description_portlet_type")
_("description_portlets_configure_1")
_("description_publishing_process")
_("description_quicksearch_users")
_("description_ratings_configure")
_("description_registered_alerts")
_("description_rename_item")
_("description_resumee")
_("description_selectcat")
_("description_selectsubject")
_("description_send_page_to")
_("description_share_folders_items_current_shares")
_("description_sharing_item")
_("description_signin_fail_cookies")
_("description_signin_fail_cookies_link")
_("description_site_error")
_("description_site_error_double_check_or_search")
_("description_speaker_job_titles")
_("description_speaker_speeches")
_("description_speaker_suffix")
_("description_still_failure")
_("description_still_failure_reason1")
_("description_still_failure_reason2")
_("description_syndication_properties")
_("description_translation_search")
_("description_versioning_disabled")
_("description_versionmanagement")
_("description_view_viewlet")
_("description_workingcopy_present")
_("description_you_are_registered")
_("description_you_can_log_on_now")
_("deselect this search parameter")
_("deselect")
_("details_about_authors")
_("disability")
_("document_type")
_("download")
_("download_full_publication")
_("draft")
_("economic_incentives")
_("edit portlet content")
_("education")
_("email_title")
_("emerging_risks")
_("empty_trash")
_("event_type")
_("events_for_this_month")
_("examples_queries")
_("extended_search_url")
_("feature_back_to_mainpage")
_("february")
_("feedback_comment")
_("feedback_country")
_("feedback_from_name")
_("feedback_link")
_("feedback_mailtemplate_body")
_("feedback_organization_size")
_("feedback_sender")
_("feedback_sender_mssg_1")
_("feedback_sender_mssg_2")
_("feedback_sender_mssg_3")
_("feedback_sender_mssg_from")
_("feedback_sender_mssg_thankyou")
_("feedback_sent_by")
_("fisheries")
_("flag_search")
_("folder")
_("folder_option")
_("folders_link")
_("foresight")
_("forward")
_("from")
_("gender")
_("go_to_calendar")
_("go_to_folder_localroles")
_("go_to_parent_url")
_("green_jobs")
_("header_active")
_("header_portlet_personalise")
_("header_title")
_("heading_actions")
_("heading_add_alert")
_("heading_add_new_item")
_("heading_add_sharing_permissions")
_("heading_add_to_calendar")
_("heading_additemtocollections")
_("heading_additemtonewsletters")
_("heading_admin_actions")
_("heading_advanced_search")
_("heading_alert_add_searchquer")
_("heading_alert_edit_searchquer")
_("heading_alerts_generalinterests")
_("heading_alerts_specialinterests")
_("heading_assign_workitem")
_("heading_authorities")
_("heading_calendar_views")
_("heading_change_ownership")
_("heading_complete_workitem")
_("heading_configure_user")
_("heading_confirmationform")
_("heading_content_nav")
_("heading_currently_assigned_shares")
_("heading_dc_grantboard")
_("heading_discussioncenter_applyforboard")
_("heading_discussioncenter_bind_board")
_("heading_discussioncenter_configure_discussionboard")
_("heading_document_actions")
_("heading_document_addattachments")
_("heading_document_editattachments")
_("heading_dynocontent_edit")
_("heading_edit_folder_properties")
_("heading_edit_item")
_("heading_edit_properties")
_("heading_ew2005_stopthatnoise")
_("heading_exception_details")
_("heading_feedback_comments")
_("heading_file_contents")
_("heading_group_shares")
_("heading_hierarchical_index")
_("heading_index_by_nace")
_("heading_index_by_providers")
_("heading_index_by_sme")
_("heading_index_by_topic")
_("heading_item_configure")
_("heading_item_managemetadata")
_("heading_latest_seminars")
_("heading_ldapresults")
_("heading_link_to")
_("heading_link_to_this_site")
_("heading_lost_password")
_("heading_manage_languages")
_("heading_memberdocs_search")
_("heading_metadata_element")
_("heading_metadata_values")
_("heading_metadataelement_renderedview")
_("heading_more_related_content")
_("heading_my_addresses")
_("heading_my_notifications")
_("heading_my_portalsettings")
_("heading_my_preferences")
_("heading_newsboard_previousnews")
_("heading_osha_siteconfig")
_("heading_oshasite_editimages")
_("heading_oshasite_editprops")
_("heading_other_national_sites")
_("heading_portlets_configure")
_("heading_pose_faqentry")
_("heading_publishing_process")
_("heading_questionnaire_result")
_("heading_quicksearch_users")
_("heading_rating_statistics")
_("heading_ratings_configure")
_("heading_registration_form")
_("heading_rename_item")
_("heading_research_organisations")
_("heading_search")
_("heading_search_case_studies")
_("heading_search_providers")
_("heading_search_results_memberdocs")
_("heading_search_results_rss")
_("heading_search_risk_assessment_tools")
_("heading_search_useful_links")
_("heading_sections")
_("heading_send_page_to")
_("heading_sign_in_failure_auth")
_("heading_signed_out")
_("heading_signin_fail_cookies")
_("heading_simple_search")
_("heading_sinconfig")
_("heading_site_error")
_("heading_social_partners")
_("heading_start_simple_process")
_("heading_syndication_properties")
_("heading_transfer_permissions")
_("heading_translator_search_results")
_("heading_views")
_("heading_welcome")
_("heading_wf_comments")
_("heading_wf_instructions")
_("heading_you_are_now_logged_in")
_("healthcare")
_("help nace code")
_("help_adresswahl")
_("help_advanced_search_database")
_("help_alert_path")
_("help_alert_schedule")
_("help_alert_titlesearchquery")
_("help_allow_discussion")
_("help_allow_rating")
_("help_also_ldap_group")
_("help_alt_url")
_("help_change_ownership")
_("help_change_status")
_("help_comment_to_link")
_("help_condition")
_("help_confidentialquestion")
_("help_confidentialquestion_answer")
_("help_confirm_password")
_("help_confirmtumpassword")
_("help_contact")
_("help_contributors")
_("help_copyrights")
_("help_country_abbrev")
_("help_criteria_field_name")
_("help_criteria_type")
_("help_data_text")
_("help_dc_standaloneboards")
_("help_decision")
_("help_description_link")
_("help_display_condition")
_("help_edit_condition")
_("help_edit_contents")
_("help_edit_form_text_text")
_("help_edit_logic_text_text")
_("help_effective_date")
_("help_email_creation")
_("help_email_creation_slc_ldap")
_("help_email_crosschecker")
_("help_email_projectmanager")
_("help_expiration_date")
_("help_external_url")
_("help_file")
_("help_first_name_creation")
_("help_folder_ruletargets")
_("help_format")
_("help_full_name_creation")
_("help_id")
_("help_include_subfolders")
_("help_inherit_criteria")
_("help_instruction")
_("help_keyword")
_("help_language_abbrev")
_("help_last_name_creation")
_("help_list_size")
_("help_login_slc_ldap")
_("help_mds_namespace_prefix")
_("help_mds_namespace_uri")
_("help_method")
_("help_mimetype")
_("help_new_keyword")
_("help_newsarticle_description")
_("help_notifications")
_("help_password_creation")
_("help_password_secret_question_creation")
_("help_password_secret_question_response_creation")
_("help_portlet_appearance")
_("help_portlet_cache_duration")
_("help_portlet_edit_popup")
_("help_portlet_edit_size")
_("help_portlet_logic_text")
_("help_presentation_text")
_("help_publisher")
_("help_publishing_comments")
_("help_ratingoptions")
_("help_search_author")
_("help_search_available_languages")
_("help_search_countries")
_("help_search_description")
_("help_search_item_type")
_("help_search_keywords")
_("help_search_new_items_since")
_("help_search_path")
_("help_search_review_status")
_("help_search_rssextension")
_("help_search_title")
_("help_selected_portlet")
_("help_send_to_mail")
_("help_shortname")
_("help_site_identifier")
_("help_slidetext")
_("help_sourcelanguages")
_("help_subobjects")
_("help_subtitle")
_("help_support_email")
_("help_syndication_max_items")
_("help_syndication_update_base")
_("help_syndication_update_frequency")
_("help_syndication_update_period")
_("help_tales_expression")
_("help_targetlanguages")
_("help_titelpost")
_("help_titelpre")
_("help_title")
_("help_topic_criteriatouse")
_("help_translation_complete")
_("help_tumzopepasswordanswer")
_("help_tumzopepasswortfrage")
_("help_upload_text")
_("help_uploads")
_("help_url")
_("help_use_portlet_box")
_("help_user_name_creation_casesensitive")
_("help_user_name_slc_ldap")
_("help_validtags")
_("help_wf_uploads")
_("horeca")
_("hour")
_("hwi")
_("id")
_("info_alert_searchagent")
_("info_allowed_content_rendering")
_("info_board_moderated")
_("info_configure_user_choosepassword")
_("info_confirmationform_confirmfollowing")
_("info_content_not_allowed")
_("info_dateformat")
_("info_discussion_allowed")
_("info_discussionboard_allowed_posters")
_("info_discussionboard_allowed_readers")
_("info_discussionboard_bindings")
_("info_discussionboard_blacklist")
_("info_discussionboard_boundto_center")
_("info_discussionboard_equivalent_roles")
_("info_discussionboard_equivalent_roles_posters")
_("info_discussionboard_equivalent_roles_readers")
_("info_discussionboard_list_article_text")
_("info_discussionboard_moderated")
_("info_discussionboard_moderators")
_("info_discussionboard_no_articles")
_("info_discussionboard_posting_restricted")
_("info_discussionboard_reading_restricted")
_("info_discussionboard_status")
_("info_discussioncenter_applyforboard")
_("info_discussioncenter_blacklist")
_("info_discussioncenter_boardclosing_allowed")
_("info_discussioncenter_discussion_allowed")
_("info_discussioncenter_list_article_text")
_("info_discussioncenter_moderated")
_("info_discussioncenter_no_boards")
_("info_discussioncenter_no_boardurl")
_("info_discussioncenter_posting_restricted")
_("info_discussioncenter_reading_restricted")
_("info_document_attachments_fileupload_notallowed")
_("info_document_filenumexceeded")
_("info_document_no_attachments")
_("info_extended_searchform")
_("info_feedback_message_checkbefore")
_("info_feedback_message_publications")
_("info_feedback_message_writemessage")
_("info_fileupload_allowed")
_("info_first_user")
_("info_folder_name")
_("info_join_form")
_("info_language_change_default")
_("info_language_copy")
_("info_language_delete")
_("info_language_unavailable")
_("info_link_to_this_site")
_("info_max_filenum")
_("info_max_filesize")
_("info_metadata_values")
_("info_metadataelement_renderedview")
_("info_newsboard_moderators")
_("info_newsletter_content_editing")
_("info_no_entry")
_("info_no_events_in_calendar")
_("info_portlet_does_not_exist")
_("info_portlet_feature_links")
_("info_portlet_personalise")
_("info_priority")
_("info_process")
_("info_questionnaire_login")
_("info_recent_changes")
_("info_reset_portlet_slots")
_("info_responsible_user")
_("info_search_translation_search")
_("info_searchinfolder")
_("info_sin_configfile")
_("info_start_simple_process")
_("info_tagfilter_syntaxvalidation")
_("info_topic_query")
_("info_transfer_permissions")
_("info_translator_search")
_("info_user_not_owner")
_("info_version_changed")
_("info_version_checked_in")
_("info_version_checked_out")
_("info_version_in_state")
_("info_wf_responsible_user")
_("is")
_("item workflow logging")
_("january")
_("july")
_("june")
_("keywords")
_("label_Login")
_("label_Viewlet")
_("label_abstract_article")
_("label_add_content")
_("label_add_item")
_("label_add_new_item")
_("label_add_to_calendar")
_("label_add_to_ical")
_("label_add_to_vcal")
_("label_admin")
_("label_affected_content")
_("label_albania")
_("label_alert_titlesearchquery")
_("label_all")
_("label_allow_discussion")
_("label_allow_rating")
_("label_allowed_content_rendering")
_("label_any_author")
_("label_any_country")
_("label_austria")
_("label_author")
_("label_avi")
_("label_back_to_errorlog")
_("label_belgium")
_("label_board_admin")
_("label_board_moderated")
_("label_body_text")
_("label_bosnia_and_herzegovina")
_("label_broaden_search")
_("label_bulgaria")
_("label_by")
_("label_category")
_("label_change_status")
_("label_checkin_message")
_("label_choose_mime")
_("label_choose_portlet_definition")
_("label_city")
_("label_click_to_hide_full_text")
_("label_click_to_see_speeches_summary")
_("label_click_to_show_full_text")
_("label_closed")
_("label_comment")
_("label_comments")
_("label_competitions")
_("label_confirm_password")
_("label_contact_email")
_("label_contact_name")
_("label_contact_phone")
_("label_contributors")
_("label_copyrights")
_("label_countries")
_("label_country_prefs")
_("label_creator")
_("label_criteria_field_name")
_("label_criteria_type")
_("label_croatia")
_("label_current_decision")
_("label_current_owner")
_("label_currentversion_edit_original")
_("label_currentversion_edit_workingcopy")
_("label_currentversion_view_original")
_("label_currentversion_view_workingcopy")
_("label_cyprus")
_("label_czech_republic")
_("label_date")
_("label_decision")
_("label_default_language")
_("label_delivery_date")
_("label_denmark")
_("label_discussion_default")
_("label_discussion_disabled")
_("label_discussion_enabled")
_("label_discussionboard_allowed_posters")
_("label_discussionboard_allowed_readers")
_("label_discussionboard_blacklist")
_("label_discussionboard_discussion_allowed")
_("label_discussionboard_equivalent_roles")
_("label_discussionboard_list_article_text")
_("label_discussionboard_moderated")
_("label_discussionboard_moderators")
_("label_discussionboard_posting_restricted")
_("label_discussionboard_reading_restricted")
_("label_discussionboard_responsibility")
_("label_discussionboard_status")
_("label_discussioncenter_blacklist")
_("label_discussioncenter_boardclosing_allowed")
_("label_discussioncenter_discussion_allowed")
_("label_discussioncenter_list_article_text")
_("label_discussioncenter_moderated")
_("label_discussioncenter_posting_restricted")
_("label_discussioncenter_reading_restricted")
_("label_discussioncenter_standaloneboards")
_("label_edit_contents")
_("label_effective_date")
_("label_email_address")
_("label_end_time")
_("label_endusergroup_prefs")
_("label_error")
_("label_error_message")
_("label_error_time")
_("label_error_type")
_("label_error_value")
_("label_estonia")
_("label_eventType")
_("label_event_announcement")
_("label_event_location")
_("label_event_type")
_("label_event_url")
_("label_exception_type")
_("label_exception_value")
_("label_existing_keywords")
_("label_expiration_date")
_("label_faq_answertext")
_("label_faq_questiontext")
_("label_female")
_("label_field_type")
_("label_file")
_("label_file_type")
_("label_files")
_("label_fileupload_allowed")
_("label_finland")
_("label_first_name")
_("label_firstname")
_("label_focalpoint")
_("label_folder_method")
_("label_france")
_("label_free_newsletter")
_("label_full_name")
_("label_germany")
_("label_glossaryentry_explanation")
_("label_go_to_more_profilesettings")
_("label_greece")
_("label_hidden")
_("label_hidden_calendar_eventsforthisday")
_("label_hungary")
_("label_iceland")
_("label_include_subfolders")
_("label_index_field")
_("label_index_type")
_("label_information_topics")
_("label_inherit_criteria")
_("label_instruction")
_("label_ireland")
_("label_is_active")
_("label_italy")
_("label_itemtype")
_("label_keywords")
_("label_kosovo")
_("label_language_prefs")
_("label_last_comment")
_("label_last_edited_by")
_("label_last_instruction")
_("label_last_name")
_("label_lastname")
_("label_latvia")
_("label_ldap_address")
_("label_ldap_adresseemail")
_("label_ldap_c/o")
_("label_ldap_confidentialquestion")
_("label_ldap_confidentialquestion_answer")
_("label_ldap_dateofbirth")
_("label_ldap_displaylanguage")
_("label_ldap_enabled_login_is")
_("label_ldap_isstandardaddress")
_("label_ldap_mobil")
_("label_ldap_nationality")
_("label_ldap_password_query")
_("label_ldap_password_response")
_("label_ldap_passwordconfirmation")
_("label_ldap_plzortland")
_("label_ldap_securityquestion")
_("label_ldap_securityquestion_answer")
_("label_ldap_setnewpassword")
_("label_ldap_sex")
_("label_ldap_strassehausnummer")
_("label_ldap_telefax")
_("label_ldap_telefon")
_("label_ldap_titelpost")
_("label_ldap_titelpre")
_("label_ldap_url")
_("label_ldapquery")
_("label_liechtenstein")
_("label_link")
_("label_lithuania")
_("label_localrole_to_assign")
_("label_localrole_typetouse")
_("label_login_for_more_services")
_("label_luxembourg")
_("label_macedonia")
_("label_mail_password")
_("label_male")
_("label_malta")
_("label_manage_languages")
_("label_max_filenum")
_("label_max_filesize")
_("label_mds_initialized")
_("label_mds_namespace_prefix")
_("label_mds_namespace_uri")
_("label_mimetype")
_("label_modified_items_since")
_("label_montenegro")
_("label_more_seminars_link")
_("label_moveto")
_("label_my_user_name_is")
_("label_name")
_("label_netherlands")
_("label_new_items_since")
_("label_new_keywords")
_("label_new_ldap_password_assigned")
_("label_new_owner")
_("label_new_title")
_("label_news_for_this_category")
_("label_newsarticle_external_url")
_("label_newsarticle_headline")
_("label_newsboard_discussion_allowed")
_("label_newsboard_moderators")
_("label_newsletter_available")
_("label_no_panels_available")
_("label_no_seminars_found")
_("label_norway")
_("label_notifications")
_("label_older_competitions")
_("label_organisation")
_("label_organization_type")
_("label_osha_Agency_ProjectManager_Email")
_("label_osha_TC_CrossChecker_Email")
_("label_osha_searchcountries")
_("label_osha_searchlanguages")
_("label_osha_support_email")
_("label_osha_uploadsource")
_("label_owned_by")
_("label_password")
_("label_password_secret_question")
_("label_password_secret_question_response")
_("label_password_will_be_mailed")
_("label_pixel")
_("label_poland")
_("label_portlet_alt_url")
_("label_portlet_appearance")
_("label_portlet_cacheduration")
_("label_portlet_cacheduration_desc")
_("label_portlet_condition_box")
_("label_portlet_condition_editicon")
_("label_portlet_data")
_("label_portlet_edit_popup")
_("label_portlet_edit_size")
_("label_portlet_editform")
_("label_portlet_editlogic")
_("label_portlet_invertediticon")
_("label_portlet_listsize")
_("label_portlet_logic")
_("label_portlet_presentation")
_("label_portlet_selectportlet")
_("label_portlet_useportletbox")
_("label_portugal")
_("label_position")
_("label_prescribe")
_("label_priority")
_("label_process")
_("label_process_description")
_("label_process_title")
_("label_profession")
_("label_profile")
_("label_projects")
_("label_publisher")
_("label_publishing_effective")
_("label_purpose")
_("label_rating_average")
_("label_rating_cumulative")
_("label_rating_numberofvotes")
_("label_rating_ratingoptions")
_("label_remember_my_name")
_("label_request_url")
_("label_resources_attachments")
_("label_responsible_user")
_("label_review_status")
_("label_rewards")
_("label_roles")
_("label_romania")
_("label_search_peersites")
_("label_search_term")
_("label_searchtext")
_("label_sector")
_("label_see_also")
_("label_select")
_("label_select_allornone")
_("label_select_group")
_("label_select_user")
_("label_select_usergroup")
_("label_seminar_attendees")
_("label_seminar_conclusions")
_("label_seminar_end_date")
_("label_seminar_further_actions")
_("label_seminar_link")
_("label_seminar_location")
_("label_seminar_logo")
_("label_seminar_organiser")
_("label_seminar_phone")
_("label_seminar_show_hour_column")
_("label_seminar_start_date")
_("label_seminar_summary")
_("label_seminar_website")
_("label_send_from")
_("label_send_to_mail")
_("label_serbia")
_("label_short_name")
_("label_sin_configfile")
_("label_size")
_("label_slovakia")
_("label_slovenia")
_("label_sourcelanguages")
_("label_spain")
_("label_spaker_first_name")
_("label_speaker_biography")
_("label_speaker_education")
_("label_speaker_email")
_("label_speaker_employer")
_("label_speaker_expertise")
_("label_speaker_image")
_("label_speaker_job_titles")
_("label_speaker_last_name")
_("label_speaker_middle_name")
_("label_speaker_nationality")
_("label_speaker_office_address")
_("label_speaker_office_city")
_("label_speaker_office_phone")
_("label_speaker_office_postal_code")
_("label_speaker_office_state")
_("label_speaker_social_partner_group")
_("label_speaker_speeches")
_("label_speaker_suffix")
_("label_speaker_web_sites")
_("label_speech_speakers")
_("label_start_time")
_("label_started_by")
_("label_state")
_("label_store_multilingual_input")
_("label_subobjects")
_("label_surname")
_("label_sweden")
_("label_switzerland")
_("label_syndication_channel_description")
_("label_syndication_channel_title")
_("label_syndication_channel_url")
_("label_syndication_max_items")
_("label_syndication_update_base")
_("label_syndication_update_frequency")
_("label_syndication_updateperiod")
_("label_synsource")
_("label_tagfilter_validtags")
_("label_targetlanguages")
_("label_time")
_("label_title")
_("label_topic_criteriatouse")
_("label_topic_query")
_("label_topic_useadvanced")
_("label_topic_usesimple")
_("label_topics_of_interest")
_("label_translation_complete")
_("label_translation_out_of_date")
_("label_turkey")
_("label_type")
_("label_united_kingdom")
_("label_up_to_elevateIT_setup")
_("label_up_to_preferences")
_("label_up_to_profilesettings")
_("label_upload_contents_optional")
_("label_uploadsource")
_("label_user")
_("label_user_group_name")
_("label_user_name")
_("label_user_name_slc_ldap")
_("label_versioning_information")
_("label_wmv")
_("label_your_mwnid")
_("labeln_project_description")
_("lable_translation_complete")
_("language")
_("language_help")
_("lastrun")
_("legend_account_details")
_("legend_acquired_roles")
_("legend_add_new_topic_criteria")
_("legend_address_info")
_("legend_addresses")
_("legend_alert_searchquery")
_("legend_assign_workitem")
_("legend_assigned_roles")
_("legend_available_groups")
_("legend_available_members")
_("legend_change_ownership")
_("legend_complete_workitem")
_("legend_completedata")
_("legend_configure")
_("legend_configure_left_slot")
_("legend_configure_right_slot")
_("legend_country_prefs")
_("legend_default_properties")
_("legend_definition")
_("legend_details")
_("legend_discussionboard_binding")
_("legend_discussionboard_settings")
_("legend_document_details")
_("legend_education")
_("legend_endusergroup_prefs")
_("legend_faqentry_details")
_("legend_file_details")
_("legend_folder_details")
_("legend_folder_rulefromexpression")
_("legend_folder_rulefrommethod")
_("legend_folder_rulefromtales")
_("legend_folder_ruletargets")
_("legend_folder_setnavigationview")
_("legend_generate_ldapquery")
_("legend_items_available")
_("legend_language_prefs")
_("legend_ldap_securityquestion")
_("legend_link_details")
_("legend_localrole_generatefile")
_("legend_login_and_password")
_("legend_memberships")
_("legend_more_information")
_("legend_newsarticle_details")
_("legend_newsarticle_from_board")
_("legend_oshaprops")
_("legend_personal_data")
_("legend_personal_details")
_("legend_portlet_details")
_("legend_portlet_details_advanced")
_("legend_process_details")
_("legend_processinstance_details")
_("legend_profession")
_("legend_profile")
_("legend_projects")
_("legend_publishing_details")
_("legend_rating_summary")
_("legend_reset_portlet_slots")
_("legend_rewards")
_("legend_search_advancedterms")
_("legend_search_global")
_("legend_search_standard_terms")
_("legend_search_terms")
_("legend_state_information")
_("legend_syndication_details")
_("legend_syndocument_details")
_("legend_topic_criteria_advanced")
_("legend_uploadsource")
_("legend_uploadusers")
_("legend_usage_settings")
_("legend_user_details")
_("legend_userroles")
_("legend_usersearch_found_users")
_("legend_usersearch_quicksearch")
_("legend_usersearch_selected_users")
_("legend_viewlet_details")
_("legislation")
_("link_address")
_("link_advanced_view")
_("link_back_to_nace")
_("link_back_to_providers")
_("link_back_to_sme")
_("link_back_to_topic")
_("link_breadcrumbs_home")
_("link_check_worklist")
_("link_errorlog_displayastext")
_("link_feedback_message")
_("link_go_to_originalversion")
_("link_go_to_workingcopy")
_("link_jump_to_last_page")
_("link_news_exturl")
_("link_news_readmore")
_("link_newsboard_recentnews")
_("link_no_keywords")
_("link_page_top")
_("link_report_link")
_("link_search_member_docs")
_("link_search_member_docs_again")
_("link_search_members")
_("link_search_members_again")
_("link_simple_view")
_("link_wf_show_comments")
_("link_wf_show_instructions")
_("link_whats_new")
_("link_xml_view")
_("list_portlet_personalise_1")
_("list_portlet_personalise_2")
_("list_portlet_personalise_3")
_("list_portlet_personalise_4")
_("listingheader_action")
_("listingheader_articles")
_("listingheader_articlesandreplies")
_("listingheader_author")
_("listingheader_comment")
_("listingheader_date")
_("listingheader_date_and_time")
_("listingheader_latestchanges")
_("listingheader_name")
_("listingheader_newsletter_sentby")
_("listingheader_newsletter_senton")
_("listingheader_order")
_("listingheader_owner")
_("listingheader_performed_by")
_("listingheader_priority")
_("listingheader_replies")
_("listingheader_status")
_("listingheader_title")
_("listingheader_type")
_("locked")
_("login_with_new_password_slc_ldap")
_("maintenance")
_("management_leadership")
_("march")
_("may")
_("migrant_workers")
_("minute")
_("month")
_("monthly")
_("move down 4")
_("move down")
_("move to bottom")
_("move to top")
_("move up 4")
_("move up")
_("msd")
_("name_of_the_folder")
_("nanotechnology")
_("needed")
_("new_folder_title")
_("news_by")
_("newsletter_copys_state")
_("newsletter_newsletter_archive")
_("newsletter_originals_state")
_("newsletter_template_copyright")
_("next")
_("no_alerts")
_("no_file_uploaded")
_("no_mail")
_("no_members_found")
_("no_metadata_values")
_("no_new_news")
_("no_slidetext_uploaded")
_("no_subject")
_("noise")
_("not allowed")
_("notification_email")
_("november")
_("number_of_messages")
_("object")
_("october")
_("of_mail_quota")
_("option_please_choose")
_("option_site_error_email_admin")
_("option_site_error_feedback_report")
_("option_site_error_feedback_support")
_("option_site_error_path")
_("option_site_error_search")
_("option_site_error_sitemap")
_("organisation")
_("osha_description_pressbox_pressreleases")
_("osha_discovernetwork_info")
_("osha_informationportlet_link")
_("osha_label_press_and_multimedia")
_("osha_label_press_room")
_("osha_nav_description_about_us")
_("osha_nav_description_background")
_("osha_nav_description_business")
_("osha_nav_description_campaigns")
_("osha_nav_description_directives")
_("osha_nav_description_disability")
_("osha_nav_description_ds")
_("osha_nav_description_forums")
_("osha_nav_description_framework")
_("osha_nav_description_funding")
_("osha_nav_description_good_practice")
_("osha_nav_description_guidelines")
_("osha_nav_description_implementation")
_("osha_nav_description_int_institutions")
_("osha_nav_description_int_programmes")
_("osha_nav_description_int_strategies")
_("osha_nav_description_int_systems")
_("osha_nav_description_istatistics")
_("osha_nav_description_legislation")
_("osha_nav_description_msds")
_("osha_nav_description_non_eu_institutions")
_("osha_nav_description_non_eu_programmes")
_("osha_nav_description_non_eu_strategies")
_("osha_nav_description_non_eu_systems")
_("osha_nav_description_noneu_statistics")
_("osha_nav_description_organisations")
_("osha_nav_description_osh_strategy")
_("osha_nav_description_osh_systems")
_("osha_nav_description_other")
_("osha_nav_description_other_iinfo")
_("osha_nav_description_press_room")
_("osha_nav_description_priority_groups")
_("osha_nav_description_programmes")
_("osha_nav_description_proposals")
_("osha_nav_description_provider")
_("osha_nav_description_publications")
_("osha_nav_description_risk_obs")
_("osha_nav_description_rpublications")
_("osha_nav_description_sector")
_("osha_nav_description_sectors")
_("osha_nav_description_sme")
_("osha_nav_description_standards")
_("osha_nav_description_statistics")
_("osha_nav_description_stress")
_("osha_nav_description_surveys")
_("osha_nav_description_systems")
_("osha_nav_description_topics")
_("osha_nav_description_young_people")
_("osha_nav_title_Accident Prevention")
_("osha_nav_title_about_us")
_("osha_nav_title_ageingworkers")
_("osha_nav_title_agriculture")
_("osha_nav_title_annual_report")
_("osha_nav_title_awards_2007")
_("osha_nav_title_background")
_("osha_nav_title_biological")
_("osha_nav_title_business")
_("osha_nav_title_calls")
_("osha_nav_title_campaigns")
_("osha_nav_title_change")
_("osha_nav_title_chemical")
_("osha_nav_title_conference")
_("osha_nav_title_construction")
_("osha_nav_title_directives")
_("osha_nav_title_director_corner")
_("osha_nav_title_disability")
_("osha_nav_title_ds")
_("osha_nav_title_education")
_("osha_nav_title_efacs")
_("osha_nav_title_eulegislation")
_("osha_nav_title_evaluation_reports")
_("osha_nav_title_factsheets")
_("osha_nav_title_fisheries")
_("osha_nav_title_forum")
_("osha_nav_title_forums")
_("osha_nav_title_framework")
_("osha_nav_title_funding")
_("osha_nav_title_gender")
_("osha_nav_title_good_practice")
_("osha_nav_title_guidelines")
_("osha_nav_title_healthcare")
_("osha_nav_title_implementation")
_("osha_nav_title_institutions")
_("osha_nav_title_int_institutions")
_("osha_nav_title_int_programmes")
_("osha_nav_title_int_strategies")
_("osha_nav_title_int_systems")
_("osha_nav_title_istatistics")
_("osha_nav_title_isurveys")
_("osha_nav_title_jobs")
_("osha_nav_title_legislation")
_("osha_nav_title_magazine")
_("osha_nav_title_msds")
_("osha_nav_title_navigation_link.2006-12-11.0084311637")
_("osha_nav_title_navigation_link.2006-12-11.0774460327")
_("osha_nav_title_navigation_link.2006-12-11.9313292189")
_("osha_nav_title_navigation_link.2006-12-11.9680652044")
_("osha_nav_title_noise")
_("osha_nav_title_non_eu_institutions")
_("osha_nav_title_non_eu_programmes")
_("osha_nav_title_non_eu_strategies")
_("osha_nav_title_non_eu_systems")
_("osha_nav_title_noneu_statistics")
_("osha_nav_title_noneu_surveys")
_("osha_nav_title_organisations")
_("osha_nav_title_osh_strategy")
_("osha_nav_title_osh_systems")
_("osha_nav_title_osheducation")
_("osha_nav_title_osm")
_("osha_nav_title_other")
_("osha_nav_title_other_iinfo")
_("osha_nav_title_partners_campaign")
_("osha_nav_title_physical")
_("osha_nav_title_press_room")
_("osha_nav_title_priority_groups")
_("osha_nav_title_programmes")
_("osha_nav_title_projects")
_("osha_nav_title_proposals")
_("osha_nav_title_provider")
_("osha_nav_title_psycho")
_("osha_nav_title_publications")
_("osha_nav_title_reports")
_("osha_nav_title_research")
_("osha_nav_title_risk_obs")
_("osha_nav_title_risks")
_("osha_nav_title_rpublications")
_("osha_nav_title_rtopics")
_("osha_nav_title_sector")
_("osha_nav_title_sectors")
_("osha_nav_title_sme")
_("osha_nav_title_standards")
_("osha_nav_title_statistics")
_("osha_nav_title_strategies")
_("osha_nav_title_stress")
_("osha_nav_title_surveys")
_("osha_nav_title_systems")
_("osha_nav_title_topics")
_("osha_nav_title_whp")
_("osha_nav_title_work_programmes")
_("osha_nav_title_young_people")
_("osha_networkportlet_info")
_("osha_networkportlet_link")
_("oshacontenttypes_amendment_view_abstract")
_("oshacontenttypes_directive_view_FullText")
_("oshacontenttypes_directive_view_FullText_of")
_("oshacontenttypes_directive_view_abstract")
_("oshacontenttypes_directive_view_amendments")
_("oshacontenttypes_directive_view_date")
_("oshacontenttypes_directive_view_modifications")
_("oshacontenttypes_directive_view_proposals")
_("oshaconttypes_directive_view_Note")
_("osheducation")
_("oshmail_header_subscribe")
_("oshmail_header_unsubscribe")
_("oshmail_intro_every_month")
_("oshmail_intro_welcome")
_("oshmail_label_enter_emaiL")
_("oshmail_list_1")
_("oshmail_list_3")
_("oshmail_list_4")
_("oshmail_list_5")
_("oshmail_list_6")
_("oshmail_list_7")
_("portlet_campaign_ew2007_title")
_("portlet_campaign_hwi_text")
_("portlet_campaign_hwi_title")
_("portlet_oshmail_email")
_("portlet_oshsearch_advanced")
_("portlet_riskob_text")
_("prevention")
_("previous article")
_("previous")
_("private")
_("published")
_("quota_alert")
_("quota_alert_message")
_("read")
_("registered_disabled")
_("replied")
_("replyto")
_("res/portal_type")
_("research")
_("results_by_author")
_("risk_assessment")
_("risks")
_("road_transport")
_("role_equivalence")
_("schedule")
_("search_criteria")
_("search_date")
_("search_in")
_("search_in_folder")
_("search_link")
_("search_results_advanced")
_("search_term")
_("searchresults")
_("select_ldappersonalizeaddress_01")
_("sendto_mailtemplate_body")
_("september")
_("show next day")
_("show next month")
_("show next week")
_("show next year")
_("show previous day")
_("show previous month")
_("show previous week")
_("show previous year")
_("sign the charter")
_("since")
_("slogan_statment_hw2010_campaign")
_("source")
_("statistics")
_("stress")
_("subheading_portlet_contents")
_("subheading_portlet_representation")
_("subject")
_("subscribe_to_oshmail_long")
_("switch to html")
_("switch to plain")
_("tabs_home")
_("text_ note")
_("text_abstract")
_("text_check_working_copies")
_("text_errlog_notfound")
_("the")
_("the_body_message")
_("the_from_field")
_("the_subject_of_message")
_("the_to_field")
_("this")
_("time_ever")
_("time_expired")
_("time_last_month")
_("time_last_week")
_("time_yesterday")
_("title")
_("title_add_to_ical")
_("title_add_to_vcal")
_("title_agency")
_("title_campaign_beinformed")
_("title_speaker")
_("to")
_("total_messages")
_("translation_search_url")
_("transport")
_("trash")
_("type your query")
_("unread")
_("up_to_thesaurus")
_("up_to_thesaurusitem_parent")
_("validation_validemail")
_("versioning_disabled")
_("visible")
_("weekly")
_("whp")
_("worker_participation")
_("worklist_editor")
_("worklist_instructions")
_("worklist_no_items")
_("worklist_process")
_("year")
_("young_people")

## Really not sure if any of these are useful
# _("- job vacancies, call for contractors")
# _("1-9 employees")
# _("10-49 employees")
# _("250 or more employees")
# _("50-249 employees")
# _("AT Austria")
# _("AU Australia")
# _("Abschicken")
# _("Academic institution")
# _("Accept Request")
# _("Accessibility")
# _("Add / Propose")
# _("Add Board")
# _("Add Dyno Content")
# _("Add Event")
# _("Add File")
# _("Add News Article")
# _("Add new items to this folder")
# _("Add this location to My Favorites")
# _("Add to selected Collections")
# _("Add to selected Newsletters")
# _("Add")
# _("Administration")
# _("Advanced Search")
# _("Advanced")
# _("Agency Information")
# _("Agency Web Features")
# _("Agency logo")
# _("Als Entwurf speichern")
# _("Amendment")
# _("Apply for new Board")
# _("Assign Local Role to Selected Group(s)")
# _("Assign Local Role to Selected User(s)")
# _("Assign")
# _("Attachments")
# _("BE Belgium")
# _("BG Bulgaria")
# _("Back to")
# _("Back")
# _("Bind Board")
# _("Bind to Center")
# _("Broken Link")
# _("Browse in articles")
# _("CAN Canada")
# _("CH Switzerland")
# _("CY Cyprus")
# _("CZ Czech Republic")
# _("Calendar week view")
# _("Calendar")
# _("Call for Contractors")
# _("Cancel")
# _("Change active state")
# _("Change")
# _("Channels")
# _("Check entry")
# _("Checkin")
# _("Checkout")
# _("Click here to view our partner websites [opens popup window]")
# _("Close Board")
# _("Close window")
# _("Collection")
# _("Comments")
# _("Complete")
# _("Configure")
# _("Contents")
# _("Copy to list")
# _("Copy to selected")
# _("Copyright")
# _("Country Code")
# _("Create default document")
# _("Current users workitems items")
# _("DE Germany")
# _("DK Denmark")
# _("Delete Folder")
# _("Delete Selected Role(s)")
# _("Delete")
# _("Directive")
# _("Disable Navigation view")
# _("Disable Syndication")
# _("Discard Changes")
# _("Discover our European &amp; International Partners")
# _("Discussion Article listing")
# _("Discussion Board listing")
# _("Discussion Board")
# _("Discussion Center")
# _("Document")
# _("Download as File")
# _("Dyno Container")
# _("EE Estonia")
# _("EL Greece")
# _("ES Spain")
# _("EU / international official institution")
# _("EU Europe")
# _("Edit")
# _("Enable Navigation view")
# _("Enable syndication")
# _("European Network")
# _("European Risk Observatory")
# _("FAQ Folder")
# _("FI Finland")
# _("FR France")
# _("File")
# _("Format")
# _("Generate File")
# _("Glossary Folder")
# _("Go")
# _("HU Hungary")
# _("Hierarchical thesaurus")
# _("History")
# _("Hygiene Association")
# _("I18NLayer")
# _("IE Ireland")
# _("ILO ILO")
# _("IOHA International Occupational")
# _("IS Iceland")
# _("IT Italy")
# _("Id")
# _("Image")
# _("Index of keywords")
# _("Individual")
# _("International Network")
# _("Internationale Nachrichten")
# _("JP Japan")
# _("Ja")
# _("Job Vacancy")
# _("Journalist")
# _("LT Lithuania")
# _("LU Luxembourg")
# _("LV Latvia")
# _("Labour inspector")
# _("Layout table")
# _("Link to our site")
# _("Link")
# _("Local Roles")
# _("Locked")
# _("Log in")
# _("Log out")
# _("Login")
# _("MT Malta")
# _("Make private")
# _("Menu")
# _("Metadata Set")
# _("Modification")
# _("Most visited")
# _("Move item down")
# _("Move item to bottom")
# _("Move item to top")
# _("Move item up")
# _("Move to")
# _("Move")
# _("My Folder")
# _("My Settings")
# _("NL Netherlands")
# _("NO Norway")
# _("Nace")
# _("Navigation")
# _("Nein")
# _("Neues Verzeichnis erstellen")
# _("News - DE")
# _("News Article")
# _("News Board")
# _("No Related Items")
# _("No Synonyms")
# _("No")
# _("Not applicable")
# _("Notify me now")
# _("OSH information online")
# _("OSH organisation")
# _("OSH practitioner")
# _("OSHMail")
# _("OSH_Article")
# _("OSH_Case")
# _("OSH_DBContent")
# _("OSH_Institute")
# _("OSH_Link")
# _("OSH_Product")
# _("OSH_Project")
# _("OSH_Publisher")
# _("OSH_Substance")
# _("OSHmail")
# _("Object locked")
# _("Open Board")
# _("Other")
# _("Our Events")
# _("Ownership")
# _("PDA version")
# _("PL Poland")
# _("PT Portugal")
# _("Perform Search")
# _("Plone Member Preferences")
# _("Portal Setup")
# _("Portal")
# _("Portlet")
# _("Portlets")
# _("Pose Question")
# _("Print")
# _("Private company")
# _("Properties")
# _("Proposal")
# _("Public company")
# _("Publish")
# _("RO Romania")
# _("RSS feed of these search results")
# _("RSS")
# _("Reassign")
# _("Refine Search")
# _("Register")
# _("Reject Request")
# _("Reject")
# _("Related Items")
# _("Remove from slot")
# _("Rename All")
# _("Report broken link")
# _("Request Discussion Board")
# _("Researcher")
# _("Reset Rating")
# _("Reset all Slots")
# _("Reset default image")
# _("Restore Version")
# _("SE Sweden")
# _("SI Slovenia")
# _("SK Slovakia")
# _("Save Settings")
# _("Save and View")
# _("Save")
# _("Search only in this folder")
# _("Search this site")
# _("See latest Reply")
# _("Select all items")
# _("Select item")
# _("Select")
# _("Send Request")
# _("Send me my password")
# _("Send to somebody")
# _("Set Permissions for Roles")
# _("Set default image")
# _("Set default language")
# _("Sharing")
# _("Show Result")
# _("Show address")
# _("Show result")
# _("Site Map")
# _("Site Update")
# _("Site&nbsp;Map")
# _("Site&nbsp;Update")
# _("Start")
# _("Student")
# _("Submit Query")
# _("Submit")
# _("Subscribe To Alert")
# _("Suggest interesting link")
# _("Syndicate Board")
# _("Syndicated Document")
# _("Syndication")
# _("Synonyms")
# _("TR Turkey")
# _("Test Notification")
# _("The OSH Network")
# _("Top of Page")
# _("Topic Document")
# _("Topic")
# _("Trade union")
# _("Training / Accreditation institution")
# _("Translation Help")
# _("Translation&nbsp;Help")
# _("Translations listing")
# _("Treelike folder structure")
# _("Type")
# _("UK United Kingdom")
# _("US NIOSH")
# _("US USA")
# _("Undo")
# _("Up")
# _("Update File")
# _("Update")
# _("Upload Users")
# _("Values")
# _("Verschieben nach")
# _("View")
# _("Visit our OSH Network")
# _("Visit to the Agency")
# _("Vote")
# _("WHO World Health Organisation")
# _("Wealth of OSH information")
# _("What is the Agency?")
# _("Worklist")
# _("Write Article")
# _("Yes")
# _("Your network to a safer and healthier working environment")
# _("Your network to a safer, healthier and more productive working environment")

