# Add i18n msgids here which do not exist in filesystem code so that
# the translation-extract script can find them

from osha.theme import OSHAMessageFactory as _

# TODO: Add defaults for all msgids

# FOP
_("heading_main_fop_portlet_albania")
_("heading_main_fop_portlet_austria")
_("heading_main_fop_portlet_belgium")
_("heading_main_fop_portlet_bosnia-and-herzegovina")
_("heading_main_fop_portlet_bulgaria")
_("heading_main_fop_portlet_croatia")
_("heading_main_fop_portlet_cyprus")
_("heading_main_fop_portlet_czech-republic")
_("heading_main_fop_portlet_denmark")
_("heading_main_fop_portlet_estonia")
_("heading_main_fop_portlet_finland")
_("heading_main_fop_portlet_france")
_("heading_main_fop_portlet_germany")
_("heading_main_fop_portlet_greece")
_("heading_main_fop_portlet_hungary")
_("heading_main_fop_portlet_iceland")
_("heading_main_fop_portlet_ireland")
_("heading_main_fop_portlet_italy")
_("heading_main_fop_portlet_kosovo-under-unscr-1244-99")
_("heading_main_fop_portlet_latvia")
_("heading_main_fop_portlet_liechtenstein")
_("heading_main_fop_portlet_lithuania")
_("heading_main_fop_portlet_luxembourg")
_("heading_main_fop_portlet_malta")
_("heading_main_fop_portlet_montenegro")
_("heading_main_fop_portlet_netherlands")
_("heading_main_fop_portlet_norway")
_("heading_main_fop_portlet_poland")
_("heading_main_fop_portlet_portugal")
_("heading_main_fop_portlet_romania")
_("heading_main_fop_portlet_serbia")
_("heading_main_fop_portlet_slovakia")
_("heading_main_fop_portlet_slovenia")
_("heading_main_fop_portlet_spain")
_("heading_main_fop_portlet_sweden")
_("heading_main_fop_portlet_switzerland")
_("heading_main_fop_portlet_the-former-yugoslav-republic-of-macedonia")
_("heading_main_fop_portlet_turkey")
_("heading_main_fop_portlet_united-kingdom")
_("label_back_to_fop_overview")

# NAPO
_("description_napo-015-safe-moves")
_("description_napo-016-lungs-at-work")
_("description_napo-017-working-together")
_("description_napo_film_1")
_("description_napo_film_11")
_("description_napo_film_12")
_("description_napo_film_13")
_("description_napo_film_14")
_("description_napo_film_2")
_("description_napo_film_3")
_("description_napo_film_4")
_("description_napo_film_5")
_("description_napo_film_6")
_("description_napo_film_7")
_("description_napo_film_8")
_("description_napo_film_9")
_("heading_napo-015-safe-moves")
_("heading_napo-015-safe-moves-episode-001-planning-for-safety")
_("heading_napo-015-safe-moves-episode-002-danger-unloading")
_("heading_napo-015-safe-moves-episode-003-poor-maintenance")
_("heading_napo-015-safe-moves-episode-004-carried-away")
_("heading_napo-015-safe-moves-episode-005-separate-ways")
_("heading_napo-015-safe-moves-episode-006-circus-number")
_("heading_napo-015-safe-moves-episode-007-unstable-load")
_("heading_napo-015-safe-moves-episode-008-clear-vision")
_("heading_napo-015-safe-moves-episode-009-danger-calling")
_("heading_napo-015-safe-moves-episode-010-the-end-game")
_("heading_napo-016-lungs-at-work")
_("heading_napo-017-working-together")
_("heading_napo-017-working-together-episode-001-working-together")
_("heading_napo-017-working-together-episode-002-bad-news")
_("heading_napo-017-working-together-episode-003-the-detail")
_("heading_napo-017-working-together-episode-004-we-can-work-it-out")
_("heading_napo-017-working-together-episode-005-speak-up")
_("heading_napo-017-working-together-episode-006-safety-pays")
_("heading_napo-017-working-together-episode-007-all-together-now")
_("label_napo_click_to_see_film")
_("napo_back_to_lesson")
_("title_napo_episode_12_1", default="Chemical risks at work")
_("title_napo_episode_12_2", default="Harmful")
_("title_napo_episode_12_3", default="Irritant")
_("title_napo_episode_12_4", default="Flammable")
_("title_napo_episode_12_5", default="Corrosive")
_("title_napo_episode_12_6", default="Toxic")
_("title_napo_episode_12_7", default="Dangerous for the environment")
_("title_napo_episode_12_8", default="The end")
_("title_napo_episode_14_1", default="Lock out")
_("title_napo_episode_14_2", default="Hidden hazards")
_("title_napo_episode_14_3", default="Don't improvise!")
_("title_napo_episode_14_4", default="In a rush")
_("title_napo_episode_14_5", default="Danger within!")
_("title_napo_episode_14_6", default="One, two, what to do?")
_("title_napo_episode_1_0", default="Best signs story")
_("title_napo_episode_1_1", default="Danger")
_("title_napo_episode_1_10", default="Safety helmet must be worn")
_("title_napo_episode_1_11", default="Rescue signs")
_("title_napo_episode_1_12", default="Rescue route")
_("title_napo_episode_1_13", default="First aid")
_("title_napo_episode_1_14", default="Fire protection signs")
_("title_napo_episode_1_15", default="Fire-extinguishing equipment")
_("title_napo_episode_1_16", default="Fire alarm system")
_("title_napo_episode_1_17", default="The end")
_("title_napo_episode_1_2", default="Danger - suspended load")
_("title_napo_episode_1_3", default="Danger - fork-lift trucks")
_("title_napo_episode_1_4", default="Prohibition signs")
_("title_napo_episode_1_5", default="No smoking")
_("title_napo_episode_1_6", default="No fork-lift trucks")
_("title_napo_episode_1_7", default="Mandantory signs")
_("title_napo_episode_1_8", default="Safety goggles must be worn")
_("title_napo_episode_1_9", default="Hearing protection must be worn")
_("title_napo_episode_2_0", default="The adventures of NAPO")
_("title_napo_episode_2_1", default="The importance of signposting")
_("title_napo_episode_2_2", default="Signposting is not sufficient")
_("title_napo_episode_2_3", default="Labels should be read")
_("title_napo_episode_2_4", default="Choose public transports")
_("title_napo_episode_2_5", default="The right protection at the right time")
_("title_napo_episode_2_6", default="Improvising means risk taking")
_("title_napo_episode_2_7", default="Each product has its own packaging")
_("title_napo_episode_2_8", default="Too much pressure is likely to be harmful")
_("title_napo_episode_2_9", default="Unsuitable material + incompetence = accident")
_("title_napo_episode_3_0", default="Scratch and sniff - chemical risks at work")
_("title_napo_episode_3_1", default="Harmful")
_("title_napo_episode_3_2", default="Irritant")
_("title_napo_episode_3_3", default="Flammable")
_("title_napo_episode_3_4", default="Corrosive")
_("title_napo_episode_3_5", default="Toxic")
_("title_napo_episode_3_6", default="Dangerous for the environment")
_("title_napo_episode_3_7", default="The end")
_("title_napo_episode_4_0", default="Clean Sweep")
_("title_napo_episode_4_1", default="Change of plan")
_("title_napo_episode_4_2", default="Work at height")
_("title_napo_episode_4_3", default="Enough is enough")
_("title_napo_episode_4_4", default="Safety plan")
_("title_napo_episode_4_5", default="Yellow card")
_("title_napo_episode_4_6", default="Bodybuilding")
_("title_napo_episode_4_7", default="Safety angels")
_("title_napo_episode_4_8", default="The end")
_("title_napo_episode_5_0", default="Napo - safe on site")
_("title_napo_episode_5_1", default="Building in safety")
_("title_napo_episode_5_2", default="Don't fall for it")
_("title_napo_episode_5_3", default="Heading for a fall")
_("title_napo_episode_5_4", default="Champions of the world")
_("title_napo_episode_5_5", default="Lightning strike")
_("title_napo_episode_5_6", default="Keep them apart")
_("title_napo_episode_5_7", default="Five star treatment")
_("title_napo_episode_5_8", default="Bad dream")
_("title_napo_episode_5_9", default="Safe landing")
_("title_napo_episode_6_0", default="Napo in stop that noise!")
_("title_napo_episode_6_1", default="Irreparable")
_("title_napo_episode_6_2", default="Didn't hear it coming ")
_("title_napo_episode_6_3", default="Noise in the office")
_("title_napo_episode_6_4", default="Problem pregnancy")
_("title_napo_episode_6_5", default="Out in the cold")
_("title_napo_episode_6_6", default="Don't make things worse")
_("title_napo_episode_6_7", default="The end")
_("title_napo_episode_7_0", default="Safe start")
_("title_napo_episode_7_1", default="Don't hesitate to ask questions")
_("title_napo_episode_7_2", default="Attention listen up")
_("title_napo_episode_7_3", default="Information overload")
_("title_napo_episode_7_4", default="Watch out for others too")
_("title_napo_episode_7_5", default="Overconfidence is dangerous")
_("title_napo_episode_7_6", default="The end")
_("title_napo_episode_8_0", default="Start")
_("title_napo_episode_8_1", default="Modern stressful times")
_("title_napo_episode_8_10", default="Hold me tight")
_("title_napo_episode_8_11", default="The end")
_("title_napo_episode_8_2", default="Divide and rule")
_("title_napo_episode_8_3", default="Radical ergonomics")
_("title_napo_episode_8_4", default="Twist and shout")
_("title_napo_episode_8_5", default="No grip")
_("title_napo_episode_8_6", default="Working height")
_("title_napo_episode_8_7", default="Bad vibrations")
_("title_napo_episode_8_8", default="The duel")
_("title_napo_episode_8_9", default="Think to move")
_("title_napo_episode_9_0", default="Introduction")
_("title_napo_episode_9_1", default="Assess the risk")
_("title_napo_episode_9_2", default="Identify the unknown")
_("title_napo_episode_9_3", default="Act on risks")
_("title_napo_episode_9_4", default="Risky combination")
_("title_napo_episode_9_5", default="Eliminate the hazard")
_("title_napo_episode_9_6", default="Safety pays")
_("title_napo_episode_9_7", default="The end")
_("title_napo_film_1")
_("title_napo_film_11")
_("title_napo_film_12")
_("title_napo_film_13")
_("title_napo_film_14")
_("title_napo_film_2")
_("title_napo_film_3")
_("title_napo_film_4")
_("title_napo_film_5")
_("title_napo_film_6")
_("title_napo_film_7")
_("title_napo_film_8")
_("title_napo_film_9")

# Subjects http://osha.europa.eu/uniqueValuesForSubject
_("accident_prevention")
_("ageing")
_("agriculture")
_("businessOSH")
_("cleaners")
_("competitions")
_("construction")
_("csr")
_("cww")
_("dangerous_substances")
_("disability")
_("disabled_people")
_("economic_incentives")
_("education")
_("esener")
_("fisheries")
_("gender")
_("green_jobs")
_("health_care")
_("healthcare")
_("horeca")
_("hwi")
_("legislation")
_("maintenance")
_("management_leadership")
_("migrant_workers")
_("msd")
_("nanotechnology")
_("noise")
_("organisation")
_("osheducation")
_("prevention")
_("provider")
_("publications")
_("research")
_("risk_assessment")
_("risk_observatory")
_("risks")
_("road_transport")
_("statistics")
_("stress")
_("transport")
_("whp")
_("worker_participation")
_("young_people")

# Already in the osha.pot file and translated
_("osha_label_press_and_multimedia")

# Months (just in case)
_("January")
_("February")
_("March")
_("April")
_("May")
_("June")
_("July")
_("August")
_("September")
_("October")
_("November")
_("December")

# These look like msgids (there's no other reason to keep them)
_("action_firstlogin_proceed")
_("april")
_("august")
_("back_to")
_("before")
_("box_about")
_("box_created_by")
_("box_last_modified")
_("box_oshmail_subscribe")
_("box_provided_by")
_("box_search_seminars")
_("box_speaker")
_("box_speeches")
_("box_this_url")
_("calendar day view")
_("convert to pdf")
_("daily")
_("day")
_("days")
_("december")
_("default")
_("delete")
_("details_about_authors")
_("document_type")
_("download")
_("download_full_publication")
_("draft")
_("edit portlet content")
_("emerging_risks")
_("event_type")
_("february")
_("feedback_comment")
_("feedback_country")
_("feedback_from_name")
_("feedback_link")
_("feedback_mailtemplate_body")
_("feedback_organization_size")
_("feedback_sender")
_("feedback_sender_mssg_1")
_("feedback_sender_mssg_2")
_("feedback_sender_mssg_3")
_("feedback_sender_mssg_from")
_("feedback_sender_mssg_thankyou")
_("feedback_sent_by")
_("foresight")
_("forward")
_("from")
_("go_to_calendar")
_("go_to_folder_localroles")
_("go_to_parent_url")
_("header_active")
_("header_portlet_personalise")
_("header_title")
_("heading_actions")
_("heading_add_to_calendar")
_("heading_advanced_search")
_("heading_alert_add_searchquer")
_("heading_alert_edit_searchquer")
_("heading_alerts_generalinterests")
_("heading_alerts_specialinterests")
_("heading_authorities")
_("heading_calendar_views")
_("heading_document_actions")
_("heading_ew2005_stopthatnoise")
_("heading_exception_details")
_("heading_feedback_comments")
_("heading_file_contents")
_("heading_hierarchical_index")
_("heading_index_by_nace")
_("heading_index_by_providers")
_("heading_index_by_sme")
_("heading_index_by_topic")
_("heading_latest_seminars")
_("heading_link_to")
_("heading_link_to_this_site")
_("heading_lost_password")
_("heading_other_national_sites")
_("heading_portlets_configure")
_("heading_questionnaire_result")
_("heading_quicksearch_users")
_("heading_research_organisations")
_("heading_search")
_("heading_search_case_studies")
_("heading_search_providers")
_("heading_search_results_memberdocs")
_("heading_search_results_rss")
_("heading_search_risk_assessment_tools")
_("heading_search_useful_links")
_("heading_sections")
_("heading_send_page_to")
_("heading_simple_search")
_("heading_site_error")
_("heading_social_partners")
_("heading_start_simple_process")
_("help_search_author")
_("help_search_available_languages")
_("help_search_countries")
_("help_search_description")
_("help_search_item_type")
_("help_search_keywords")
_("help_search_new_items_since")
_("help_search_path")
_("help_search_review_status")
_("help_search_rssextension")
_("help_search_title")
_("help_send_to_mail")
_("hour")
_("id")
_("info_alert_searchagent")
_("info_feedback_message_checkbefore")
_("info_feedback_message_publications")
_("info_feedback_message_writemessage")
_("is")
_("january")
_("july")
_("june")
_("keywords")
_("label_add_to_calendar")
_("label_add_to_ical")
_("label_add_to_vcal")
_("label_albania")
_("label_alert_titlesearchquery")
_("label_all")
_("label_austria")
_("label_author")
_("label_avi")
_("label_belgium")
_("label_bosnia_and_herzegovina")
_("label_broaden_search")
_("label_bulgaria")
_("label_by")
_("label_category")
_("label_city")
_("label_click_to_hide_full_text")
_("label_click_to_see_speeches_summary")
_("label_click_to_show_full_text")
_("label_closed")
_("label_comment")
_("label_comments")
_("label_competitions")
_("label_contact_email")
_("label_contact_name")
_("label_contact_phone")
_("label_contributors")
_("label_copyrights")
_("label_countries")
_("label_creator")
_("label_croatia")
_("label_current_decision")
_("label_cyprus")
_("label_czech_republic")
_("label_date")
_("label_default_language")
_("label_denmark")
_("label_estonia")
_("label_faq_answertext")
_("label_faq_questiontext")
_("label_female")
_("label_finland")
_("label_first_name")
_("label_firstname")
_("label_focalpoint")
_("label_folder_method")
_("label_france")
_("label_free_newsletter")
_("label_full_name")
_("label_germany")
_("label_greece")
_("label_hidden")
_("label_hungary")
_("label_iceland")
_("label_include_subfolders")
_("label_ireland")
_("label_italy")
_("label_keywords")
_("label_kosovo")
_("label_latvia")
_("label_liechtenstein")
_("label_lithuania")
_("label_luxembourg")
_("label_macedonia")
_("label_male")
_("label_malta")
_("label_montenegro")
_("label_more_seminars_link")
_("label_my_user_name_is")
_("label_name")
_("label_netherlands")
_("label_no_seminars_found")
_("label_norway")
_("label_notifications")
_("label_older_competitions")
_("label_osha_searchcountries")
_("label_osha_searchlanguages")
_("label_osha_support_email")
_("label_osha_uploadsource")
_("label_poland")
_("label_portugal")
_("label_position")
_("label_prescribe")
_("label_priority")
_("label_process")
_("label_process_description")
_("label_process_title")
_("label_profession")
_("label_profile")
_("label_projects")
_("label_publisher")
_("label_publishing_effective")
_("label_purpose")
_("label_romania")
_("label_sector")
_("label_see_also")
_("label_select")
_("label_send_from")
_("label_send_to_mail")
_("label_serbia")
_("label_size")
_("label_slovakia")
_("label_slovenia")
_("label_spain")
_("label_start_time")
_("label_surname")
_("label_sweden")
_("label_switzerland")
_("label_time")
_("label_title")
_("label_topics_of_interest")
_("label_turkey")
_("label_type")
_("label_united_kingdom")
_("language")
_("language_help")
_("legend_alert_searchquery")
_("legend_profession")
_("legend_search_global")
_("link_address")
_("link_breadcrumbs_home")
_("link_page_top")
_("link_report_link")
_("list_portlet_personalise_1")
_("list_portlet_personalise_2")
_("list_portlet_personalise_3")
_("list_portlet_personalise_4")
_("listingheader_action")
_("listingheader_articles")
_("listingheader_articlesandreplies")
_("listingheader_author")
_("listingheader_comment")
_("listingheader_date")
_("listingheader_date_and_time")
_("listingheader_latestchanges")
_("listingheader_name")
_("listingheader_newsletter_sentby")
_("listingheader_newsletter_senton")
_("listingheader_order")
_("listingheader_owner")
_("listingheader_performed_by")
_("listingheader_priority")
_("listingheader_replies")
_("listingheader_status")
_("listingheader_title")
_("listingheader_type")
_("locked")
_("march")
_("may")
_("minute")
_("month")
_("monthly")
_("needed")
_("news_by")
_("next")
_("no_alerts")
_("no_subject")
_("not allowed")
_("notification_email")
_("november")
_("october")
_("osha_description_pressbox_pressreleases")
_("osha_discovernetwork_info")
_("osha_informationportlet_link")
_("osha_label_press_and_multimedia")
_("osha_label_press_room")
_("osha_networkportlet_info")
_("osha_networkportlet_link")
_("oshmail_header_subscribe")
_("oshmail_header_unsubscribe")
_("oshmail_intro_every_month")
_("oshmail_intro_welcome")
_("oshmail_label_enter_emaiL")
_("oshmail_list_1")
_("oshmail_list_3")
_("oshmail_list_4")
_("oshmail_list_5")
_("oshmail_list_6")
_("oshmail_list_7")
_("portlet_campaign_ew2007_title")
_("portlet_campaign_hwi_text")
_("portlet_campaign_hwi_title")
_("portlet_oshmail_email")
_("portlet_oshsearch_advanced")
_("portlet_riskob_text")
_("results_by_author")
_("role_equivalence")
_("schedule")
_("search_criteria")
_("search_date")
_("search_in")
_("search_in_folder")
_("search_link")
_("search_results_advanced")
_("search_term")
_("searchresults")
_("september")
_("show next day")
_("show next month")
_("show next week")
_("show next year")
_("show previous day")
_("show previous month")
_("show previous week")
_("show previous year")
_("sign the charter")
_("since")
_("slogan_statment_hw2010_campaign")
_("source")
_("subheading_portlet_contents")
_("subheading_portlet_representation")
_("subject")
_("subscribe_to_oshmail_long")
_("tabs_home")
_("title")
_("title_add_to_ical")
_("title_add_to_vcal")
_("title_agency")
_("title_campaign_beinformed")
_("title_speaker")
_("to")
_("total_messages")
_("type your query")
_("visible")
_("weekly")
_("year")

## Really not sure if any of these are useful
# _("- job vacancies, call for contractors")
# _("1-9 employees")
# _("10-49 employees")
# _("250 or more employees")
# _("50-249 employees")
# _("AT Austria")
# _("AU Australia")
# _("Abschicken")
# _("Academic institution")
# _("Accept Request")
# _("Accessibility")
# _("Add / Propose")
# _("Add Board")
# _("Add Dyno Content")
# _("Add Event")
# _("Add File")
# _("Add News Article")
# _("Add new items to this folder")
# _("Add this location to My Favorites")
# _("Add to selected Collections")
# _("Add to selected Newsletters")
# _("Add")
# _("Administration")
# _("Advanced Search")
# _("Advanced")
# _("Agency Information")
# _("Agency Web Features")
# _("Agency logo")
# _("Als Entwurf speichern")
# _("Amendment")
# _("Apply for new Board")
# _("Assign Local Role to Selected Group(s)")
# _("Assign Local Role to Selected User(s)")
# _("Assign")
# _("Attachments")
# _("BE Belgium")
# _("BG Bulgaria")
# _("Back to")
# _("Back")
# _("Bind Board")
# _("Bind to Center")
# _("Broken Link")
# _("Browse in articles")
# _("CAN Canada")
# _("CH Switzerland")
# _("CY Cyprus")
# _("CZ Czech Republic")
# _("Calendar week view")
# _("Calendar")
# _("Call for Contractors")
# _("Cancel")
# _("Change active state")
# _("Change")
# _("Channels")
# _("Check entry")
# _("Checkin")
# _("Checkout")
# _("Click here to view our partner websites [opens popup window]")
# _("Close Board")
# _("Close window")
# _("Collection")
# _("Comments")
# _("Complete")
# _("Configure")
# _("Contents")
# _("Copy to list")
# _("Copy to selected")
# _("Copyright")
# _("Country Code")
# _("Create default document")
# _("Current users workitems items")
# _("DE Germany")
# _("DK Denmark")
# _("Delete Folder")
# _("Delete Selected Role(s)")
# _("Delete")
# _("Directive")
# _("Disable Navigation view")
# _("Disable Syndication")
# _("Discard Changes")
# _("Discover our European &amp; International Partners")
# _("Discussion Article listing")
# _("Discussion Board listing")
# _("Discussion Board")
# _("Discussion Center")
# _("Document")
# _("Download as File")
# _("Dyno Container")
# _("EE Estonia")
# _("EL Greece")
# _("ES Spain")
# _("EU / international official institution")
# _("EU Europe")
# _("Edit")
# _("Enable Navigation view")
# _("Enable syndication")
# _("European Network")
# _("European Risk Observatory")
# _("FAQ Folder")
# _("FI Finland")
# _("FR France")
# _("File")
# _("Format")
# _("Generate File")
# _("Glossary Folder")
# _("Go")
# _("HU Hungary")
# _("Hierarchical thesaurus")
# _("History")
# _("Hygiene Association")
# _("I18NLayer")
# _("IE Ireland")
# _("ILO ILO")
# _("IOHA International Occupational")
# _("IS Iceland")
# _("IT Italy")
# _("Id")
# _("Image")
# _("Index of keywords")
# _("Individual")
# _("International Network")
# _("Internationale Nachrichten")
# _("JP Japan")
# _("Ja")
# _("Job Vacancy")
# _("Journalist")
# _("LT Lithuania")
# _("LU Luxembourg")
# _("LV Latvia")
# _("Labour inspector")
# _("Layout table")
# _("Link to our site")
# _("Link")
# _("Local Roles")
# _("Locked")
# _("Log in")
# _("Log out")
# _("Login")
# _("MT Malta")
# _("Make private")
# _("Menu")
# _("Metadata Set")
# _("Modification")
# _("Most visited")
# _("Move item down")
# _("Move item to bottom")
# _("Move item to top")
# _("Move item up")
# _("Move to")
# _("Move")
# _("My Folder")
# _("My Settings")
# _("NL Netherlands")
# _("NO Norway")
# _("Nace")
# _("Navigation")
# _("Nein")
# _("Neues Verzeichnis erstellen")
# _("News - DE")
# _("News Article")
# _("News Board")
# _("No Related Items")
# _("No Synonyms")
# _("No")
# _("Not applicable")
# _("Notify me now")
# _("OSH information online")
# _("OSH organisation")
# _("OSH practitioner")
# _("OSHMail")
# _("OSH_Article")
# _("OSH_Case")
# _("OSH_DBContent")
# _("OSH_Institute")
# _("OSH_Link")
# _("OSH_Product")
# _("OSH_Project")
# _("OSH_Publisher")
# _("OSH_Substance")
# _("OSHmail")
# _("Object locked")
# _("Open Board")
# _("Other")
# _("Our Events")
# _("Ownership")
# _("PDA version")
# _("PL Poland")
# _("PT Portugal")
# _("Perform Search")
# _("Plone Member Preferences")
# _("Portal Setup")
# _("Portal")
# _("Portlet")
# _("Portlets")
# _("Pose Question")
# _("Print")
# _("Private company")
# _("Properties")
# _("Proposal")
# _("Public company")
# _("Publish")
# _("RO Romania")
# _("RSS feed of these search results")
# _("RSS")
# _("Reassign")
# _("Refine Search")
# _("Register")
# _("Reject Request")
# _("Reject")
# _("Related Items")
# _("Remove from slot")
# _("Rename All")
# _("Report broken link")
# _("Request Discussion Board")
# _("Researcher")
# _("Reset Rating")
# _("Reset all Slots")
# _("Reset default image")
# _("Restore Version")
# _("SE Sweden")
# _("SI Slovenia")
# _("SK Slovakia")
# _("Save Settings")
# _("Save and View")
# _("Save")
# _("Search only in this folder")
# _("Search this site")
# _("See latest Reply")
# _("Select all items")
# _("Select item")
# _("Select")
# _("Send Request")
# _("Send me my password")
# _("Send to somebody")
# _("Set Permissions for Roles")
# _("Set default image")
# _("Set default language")
# _("Sharing")
# _("Show Result")
# _("Show address")
# _("Show result")
# _("Site Map")
# _("Site Update")
# _("Site&nbsp;Map")
# _("Site&nbsp;Update")
# _("Start")
# _("Student")
# _("Submit Query")
# _("Submit")
# _("Subscribe To Alert")
# _("Suggest interesting link")
# _("Syndicate Board")
# _("Syndicated Document")
# _("Syndication")
# _("Synonyms")
# _("TR Turkey")
# _("Test Notification")
# _("The OSH Network")
# _("Top of Page")
# _("Topic Document")
# _("Topic")
# _("Trade union")
# _("Training / Accreditation institution")
# _("Translation Help")
# _("Translation&nbsp;Help")
# _("Translations listing")
# _("Treelike folder structure")
# _("Type")
# _("UK United Kingdom")
# _("US NIOSH")
# _("US USA")
# _("Undo")
# _("Up")
# _("Update File")
# _("Update")
# _("Upload Users")
# _("Values")
# _("Verschieben nach")
# _("View")
# _("Visit our OSH Network")
# _("Visit to the Agency")
# _("Vote")
# _("WHO World Health Organisation")
# _("Wealth of OSH information")
# _("What is the Agency?")
# _("Worklist")
# _("Write Article")
# _("Yes")
# _("Your network to a safer and healthier working environment")
# _("Your network to a safer, healthier and more productive working environment")

